### ISSUE TITLE
标签与分类页面渲染为关于页面

### ISSUE THREAD

**Issue by sssomeone** [abelsu7/hexo-theme-indigo-plus#3]
![](https://ws1.sinaimg.cn/large/007EY3Ilgy1g58u1oahs0j31hc0sm7ak.jpg)
这样子，不显示分类内容

**Comment by abelsu7** [comment]
要设置对应的 layout，例如`source/tags/index.md`：

```yaml
---
title: tags
date: 2018-02-05 17:47:53
layout: tags
comments: false
---
```
